image: echocat/kubor:v0.4.8
services:
  - docker:dind

variables:
  KUBOR_RELEASE: $CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  KUBOR_LOG_COLOR_MODE: always

stages:
  - test:unit
  - build
  - test:integration
  - deploy:development
  - deploy:pre-production
  - deploy:production

test:code:
  image: golang:1.12
  stage: test:unit
  cache:
    key: go-cache
    paths:
      - .go
  variables:
    GOPATH: "$CI_PROJECT_DIR/.go"
  except:
    variables:
      - $CI_UNIT_TESTS == "skip"
      - $CI_ALL_TESTS == "skip"
  before_script:
    - go mod download
  script:
    - go run github.com/gobuffalo/packr/packr clean
    - go run github.com/gobuffalo/packr/packr -z -i fallback
    - go test -v ./...

build:
  stage: build
  cache:
    key: go-cache
    paths:
      - .go
  variables:
    IMAGE: "echocat/lingress"
  before_script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build --network host -t $IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA --build-arg "REVISION=$CI_COMMIT_SHA" --build-arg "BRANCH=$CI_COMMIT_REF_NAME" --build-arg "SSH_PRIVATE_KEY=$SSH_PRIVATE_KEY" .
    - docker tag  $IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA $IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker push $IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE/$CI_COMMIT_REF_NAME:latest
