groupId: echocat
artifactId: lingress

values:
  - podMinMemory:            64Mi
    podMaxMemory:            256Mi
    podMinCpu:               250m
    podMaxCpu:               500m
    replicas:                1
    logLevel:                info
    behindOtherReverseProxy: 'true'
    corsEnabled:             'false'
    forceSecureEnabled:      '!false'
