{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "lingress.fullname" . }}
  labels:
    {{- include "lingress.labels" . | nindent 4 }}
    {{- with .Values.rbac.labels -}}{{- . | toYaml | nindent 4 -}}{{- end }}
  annotations:
    {{- include "lingress.annotations" . | nindent 4 }}
    {{- with .Values.rbac.annotations -}}{{- . | toYaml | nindent 4 -}}{{- end }}
rules:
  - apiGroups:
      - ''
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list
      - watch
{{ end }}
