{{ if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "lingress.serviceAccountName" . }}
  namespace: {{ template "lingress.namespace" . }}
  labels:
    {{- include "lingress.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels -}}{{- . | toYaml | nindent 4 -}}{{- end }}
  annotations:
    {{- include "lingress.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations -}}{{- . | toYaml | nindent 4 -}}{{- end }}
{{ end }}
