{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lingress.fullname" . }}
  namespace: {{ template "lingress.namespace" . }}
  labels:
    {{- include "lingress.labels" . | nindent 4 }}
    {{- with .Values.service.labels -}}{{- . | toYaml | nindent 4 -}}{{- end }}
  annotations:
    {{- include "lingress.annotations" . | nindent 4 }}
    {{- with .Values.service.annotations -}}{{- . | toYaml | nindent 4 -}}{{- end }}
spec:
  ports:
    - port: {{.Values.service.ports.http}}
      targetPort: http
    - port: {{.Values.service.ports.https}}
      targetPort: https
  selector:
    {{- include "lingress.selectorLabels" . | nindent 4 }}
  type: {{.Values.service.type}}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{. | quote}}
  {{- end}}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{. | quote}}
  {{- end}}
{{ end }}
