apiVersion: v1
kind: Service
metadata:
  name: {{.ArtifactId}}
  namespace: {{.GroupId}}
spec:
  selector:
    name: {{.ArtifactId}}
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management
      protocol: TCP
      port: 8090
      targetPort: 8090
